sudo: required

dist: trusty

notifications:
  email: false

language: java

services: docker

before_install:
  - chmod +x gradlew

before_script:
  - docker-compose build

script:
  - docker-compose up -d