sudo: required

dist: trusty

notifications:
  email: false

language: java

env:
  - DOCKER_COMPOSE_VERSION=1.29.1

services: docker

before_install:
  - chmod +x gradlew

before_script:
  - sudo docker-compose build

script:
  - sudo docker-compose up -d